#!/bin/bash

COMMAND="$1"
STATE=hostcfg.state

APP_DIR=/srv/simple-web-app

do_begin() {
	rm -rf $STATE
	mkdir -p $STATE/app
}

do_set() {
    PROPNAME="$1"
    case "$PROPNAME" in

	issuer_url)
	    echo idp.url=$(cat) > $STATE/app/issuer
	    ;;

	auth_url)
	    echo idp.authorization.url=$(cat) > $STATE/app/auth
	    ;;

	token_url)
	    echo idp.token.url=$(cat) > $STATE/app/token
	    ;;

	userinfo_url)
	    echo idp.userInfo.url=$(cat) > $STATE/app/userinfo
	    ;;

	jwks_url)
	    echo idp.jwks.url=$(cat) > $STATE/app/jwks
	    ;;

	client_id)
	    echo TODO
	    ;;

	client_secret)
	    echo TODO
	    ;;

	*)
	    echo UNKNOWN PROPERTY: $PROPNAME
	    exit 1
	    ;;
    esac
}


do_get() {
    PROPNAME="$1"
    case "$PROPNAME" in
	client_name)
	    echo simple-web-app
	    ;;

	redirect_uris)
	    echo " - http://$(unit-get public-address)/openid_connect_login"
	    ;;
	
	description)
	    echo A very simple web application
	    ;;
	
	*)
	    echo UNKNOWN PROPERTY: $PROPNAME
	    exit 1
    esac
}


do_default() {
    ISSUER_URL=http://localhost:8080/openid-connect-server-webapp/
    echo $ISSUER_URL            | do_set issuer_url
    echo ${ISSUER_URL}authorize | do_set auth_url
    echo ${ISSUER_URL}token     | do_set token_url
    echo ${ISSUER_URL}userinfo  | do_set userinfo_url
    echo ${ISSUER_URL}jwk       | do_set jwks_url
}


do_commit() {
    
    # reconfigure
    cat $STATE/app/* > $APP_DIR/src/main/webapp/WEB-INF/spring/application.properties
    rm -rf $STATE
    
    # restart
    /srv/simple-web-app/stop
    /srv/simple-web-app/start & 
    disown
}


case "$1" in

     'begin')
	do_begin
	;;

    'default')
	do_default
	;;

    'set')
	do_set "$2"
	;;

    'get')
	do_get "$2"
	;;

    'commit')
	do_commit
	;;

    *)
	echo UNKNOWN COMMAND: "'$1'"
	exit 1
	;;

esac
